apiVersion: 1

datasources:
  - name: InfluxDB
    uid: agrodrone-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: agrodrone
      defaultBucket: telemetry
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: false
